### ISSUE TITLE
Animation does not load [perm.in.anim.2]

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#668] opened 2018-01-12 15:25 UTC
This is a bug in #503 

The following action is broken in Edge, Chrome, and FireFox (tested on Windows). Works in IE11.

Test plan code: perm.in.anim.2

/?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,AIRS_CO_Total_Column_Day(palette=red_1),Reference_Labels(hidden),Reference_Features(hidden),Coastlines&t=2016-09-25&z=3&v=-200.7421875,-49.2890625,0.2109375,55.7578125&ab=on&as=2016-09-21&ae=2016-09-28&av=3&al=true

- Page should load with animation widget activated and a custom colormap active
- When you press play the animation should start and loop

**Comment by minniewong** [comment] 2018-01-12 15:31
Also Chrome OSX

**Comment by localjo** [comment] 2018-01-12 16:15
Duplicate of #667

**Closed by localjo** 2018-01-12 16:15 UTC
