### ISSUE TITLE
document grunt tasks

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#402] opened 2017-07-14 15:25 UTC
fetch -> no current documentation
config -> documentation needs more detail

**Comment by localjo** [comment] 2017-08-03 20:06
There's a CoffeeScript task that can probably be removed, and we can just use the JS source instead of the CoffeeScript source.

**Comment by Benjaki2** [comment] 2017-08-04 22:21
👍  I've been wanting to out that coffeescript for a while now

**Comment by ZachTRice** [comment] 2017-09-14 17:36
Possible duplicate of #312

**Comment by ZachTRice** [comment] 2018-01-23 16:56
These notes have been updated in 2.0

**Closed by ZachTRice** 2018-01-23 16:56 UTC
