### ISSUE TITLE
Tooltip "Fire" on hover, intermitten showing up/not

### ISSUE THREAD

**Issue by npressley** [nasa-gibs/worldview#2930] opened 2020-06-03 16:32 UTC
Mac/Chrome:
(Minnie also sees this in Firefox)

in SIT/Chrome, something weird seems to be happening (https://go.nasa.gov/2zNeyiB)

When I hover over a fire, sometimes the tooltip doesn't show up, sometimes it does.

Failing on this [test plan](https://wiki.earthdata.nasa.gov/display/WOR/S-12+%5Bsetting%5D%3A+Layer+Settings):

layer.legend.4

**Comment by jasontk19** [comment] 2020-06-04 14:23
This issue also appears in production (and may go back several version).  It appears the problem is that the hex value being reported by OpenLayers does not match up with the color provided by the legend. The reported hex value seems to vary quite a bit and only occasionally comes close enough to be considered a match.


![Screen Shot 2020-06-04 at 10 21 51 AM](https://user-images.githubusercontent.com/1480000/83768849-3af44100-a64d-11ea-857f-
485adfd6df08.png)

**Comment by jasontk19** [comment] 2020-06-04 15:09
Here's an up close examination of a single PNG tile served by GIBS for this layer.  You can see the pixel values vary quite a bit.  Not sure I'm going about this the right way but I'm wondering if something changed on the GIBS side in relation to how these tiles are generated?

![hexValues](https://user-images.githubusercontent.com/1480000/83774433-b0631000-a653-11ea-98c0-97e93cdedda6.gif)

**Comment by jasontk19** [comment] 2020-06-04 15:17
Since raster fire layers will be replaced with vector layers in the near term, and since the code surrounding this functionality is different depending on tile type, we are going to close this as a "won't fix" for now.

**Closed as completed by jasontk19** 2020-06-04 15:17 UTC
Labels: bug, wontfix, SIT
