### ISSUE TITLE
Compile error version 1.4.5

### ISSUE THREAD

**Issue by pombero** [nasa-gibs/worldview#309] opened 2017-05-26 17:07 UTC
I tried to grunt worldview with worldview-options-eosdis v1.4.5 and i get the following message with warnings and one error:

>> wv-options-validate:  WARN: [ASTER_L1T_Radiance_Terrain_Corrected] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [Graticule_Reverb] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [Blue_Marble_Reverb] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [SMAP_L3_Passive_Soil_Moisture] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [MERRA_Surface_Pressure_Monthly] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [Blue_Marble] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [SCAR_Land_Mask] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [SMAP_L2_Passive_Soil_Moisture_Option1] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [SMAP_L2_Passive_Soil_Moisture_Option2] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [SMAP_L2_Passive_Soil_Moisture_Option3] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [AIRS_Dust_Score] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [OSM_Land_Mask] Unexpected layer, not in layer order
>> wv-options-validate: ERROR: [OMI_Nitrogen_Dioxide_Tropo_Column] No projections defined or not found in GC documents
>> wv-options-validate:  WARN: [OMI_Nitric_Oxide_Tropo_Column] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [CERES_Combined_TOA_Shortwave_Flux_All_Sky_Monthly] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [MERRA_Surface_Skin_Temperature_Monthly] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [Sea_Surface_Temp_Infrared] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [SCAR_Land_Water_Map] Unexpected layer, not in layer order
>> wv-options-validate:  WARN: [OSM_Land_Water_Map] Unexpected layer, not in layer order
wv-options-validate: 1 error(s), 18 warning(s), 19 removed
>> Exited with code: 1.
Warning: Task "exec:config" failed. Use --force to continue.

nvm v0.33.2
node v6.8.1
npm v3.10.8
Ubuntu 14.04.5 LTS 64-bits

**Comment by rboller** [comment] 2017-05-26 20:47
Hi @pombero, I believe this is caused by a recent name change of the OMI Nitrogen Dioxide layer to `OMI_Nitrogen_Dioxide_Tropo_Column`.  If you perform a `grunt fetch`, it will retrieve the latest list of layers from the GIBS GetCapabilities document including this renamed one.  You should then be able to build using `grunt`.

If this doesn't do the trick, please reopen this ticket.

**Comment by rboller** [comment] 2017-05-26 21:39
Actually the problem looks to be on the GIBS side - when the Worldview grunt is at this stage:

> Running "exec:config" (exec) task
wv-options-wmts: 0 error(s), 0 warning(s), 501 layers for GIBS:geographic
wv-options-wmts: 0 error(s), 0 warning(s), 55 layers for GIBS:arctic
wv-options-wmts: 0 error(s), 0 warning(s), 44 layers for GIBS:antarctic
wv-options-wmts: 0 error(s), 0 warning(s), 600 layers

it should show 501 geographic layers as of today.... but on some builds, it only retrieves 500 layers and the new OMI Nitrogen Dioxide layer appears to be missing and causing the build problem you see.  My recommended workaround at this point is to run `grunt` as many times as you need until the OMI layer is included.   Will keep this ticket open until it's fixed on our side.

**Comment by rboller** [comment] 2017-05-26 22:26
So I'm going to retract my last comment there - a `grunt fetch` and then `grunt` should've solved the problem originally.  

But that shouldn't be necessary if you're working from a clean build or pull latest from master, so I've now updated the options repo to have everything you need to build.  So if you go to the options directory and perform a `git pull` and then `grunt`, everything _should_ work!  Please let me know if that's not the case.

On a side note, if you're making frequent updates to the layer configuration but don't want to rebuild the whole app every time, you can use the `grunt config` command (as documented [here](https://github.com/nasa-gibs/worldview/blob/master/doc/developing.md#configuration)) to only rebuild the layer config.

**Closed by rboller** 2017-05-26 22:26 UTC
