### ISSUE TITLE
Animation widget is not hidden when you select data download [date.animation.15]

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#676] opened 2018-01-12 20:54 UTC
Animation should be hidden when you click on data download

**Comment by minniewong** [comment] 2018-01-12 21:00
except after refreshing, i couldn't replicate the problem!

**Comment by ZachTRice** [comment] 2018-01-17 17:51
I am not able to reproduce this in Chrome, Firefox, Edge, or IE. Were you able to reproduce this again @minniewong? If you can't reproduce it then I think this might have just been a glitch and we can close this issue.

**Comment by minniewong** [comment] 2018-01-17 17:51
no i couldn't replicate it...

**Closed** 2018-01-17 17:57 UTC
Labels: invalid
