### ISSUE TITLE
Can drag animation date draggers to future dates [date.animation.8]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#901] opened 2018-04-20 16:02 UTC
In the 'set up animation' for GIF, user can drag animation draggers beyond today's date. Expected to be limited to selecting a max range of today's date.

**Steps to repeat:**
1. open 'set up animation' GIF dialog (daily increments selected by default)
2. drag left dragger as far as it can go to the right and make sure your drag mouseovers the right (end date) animation dragger
3. draggers should be on future dates and not visible on the timeline

Likely related to **Dragging animation end date guitar pick past timeline end causes wonky behavior [date.animation.9]** [#679](https://github.com/nasa-gibs/worldview/issues/679)

**Comment by minniewong** [comment] 2018-05-24 19:14
I see this issue in Firefox too - draggers end up off the timeline and you can't see them anymore

**Comment by minniewong** [comment] 2018-06-14 19:15
If you are in the Year increments in the animation mode and you drag the draggers off the map, the year in the animation widget can change to 2020.

**Comment by minniewong** [comment] 2018-07-16 15:46
Duplicate of #1105

**Closed by minniewong** 2018-07-16 15:46 UTC
Labels: bug
