### ISSUE TITLE
Check GIBS Google Maps example

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#122] opened 2017-01-25 19:58 UTC
https://github.com/nasa-gibs/gibs-web-examples#google-maps
https://earthdata.nasa.gov/labs/gibs/examples/google/webmercator-epsg3857.html

**Comment by rboller** [comment] 2017-01-26 17:20
The problem is on the GIBS side - during MODIS C6 atmosphere reprocessing, the older web mercator imagery was deleted and is currently being done on a forward processing basis.  

Eventually this will be addressed by GIBS' on-the-fly reprojection.  Until then, they agreed to reprocess the single date used in the GIBS Web Examples.  More details in GIBS-1969.

**Closed** 2017-04-27 20:22 UTC

**Comment by rboller** [comment] 2017-04-27 20:27
GIBS backfilled that date and the examples work again
