### ISSUE TITLE
Update end date in timeline if browser is open for more than a day

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#409] opened 2017-07-17 16:56 UTC
We should also allow the user to advance the date if they kept the browser open long enough where it's the next day. As it currently stands, the app's last date available is fixed at load time.
Connect to #389

**Comment by localjo** [comment] 2017-08-01 15:30
I think this is a duplicate of #389 and can be tackled at the same time.

**Closed by localjo** 2017-08-01 15:30 UTC
