### ISSUE TITLE
Better error handling for EONET

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#963] opened 2018-05-04 17:47 UTC
From WV-1789: If there are errors retrieving events from EONET, Worldview currently prints a cryptic message to the console and the UI doesn't show anything. This ticket is to catch those errors more gracefully.

**Comment by rboller** [comment] 2019-06-11 22:18
Closing this ticket as mostly a duplicate of #1727 (even though this one was first :)

**Closed by rboller** 2019-06-11 22:18 UTC
Labels: investigate
