### ISSUE TITLE
Need new data handler for MISR NRT

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#344] opened 2017-06-19 14:24 UTC
Current data handlers don't work very well for MISR NRT

**Comment by minniewong** [comment] 2017-06-19 14:30
"List" data handler shows a long list of dates/times and I don't know if we need a different handler for each camera angle
![list_datahandler](https://user-images.githubusercontent.com/10747923/27290098-27c7c182-54da-11e7-9c1d-14dddddcf783.jpg)
![list_datahandler_2](https://user-images.githubusercontent.com/10747923/27290099-28ecd214-54da-11e7-905e-8a700532307c.jpg)

**Comment by minniewong** [comment] 2017-06-19 14:31
"MODISSwath" data handler shows a lot of points really close to each other, but is easier visualized than the list?
![modisswath_datahandler](https://user-images.githubusercontent.com/10747923/27290154-5f7ff450-54da-11e7-9108-2d5d056fb348.jpg)

**Comment by rboller** [comment] 2017-06-22 22:34
Duplicate of #352

**Closed by rboller** 2017-06-22 22:34 UTC
Labels: duplicate
