### ISSUE TITLE
Animation playback interval should default to current timeline interval

### ISSUE THREAD

**Issue by dattilo** [nasa-gibs/worldview#1612] opened 2019-01-25 23:57 UTC
Hi Worldview Team,
   I hope all is going as well as can be in your neck of the woods... We have been adding layers to worldview and now have 16 layers displaying our 10day forecast for the WACCM model. We are eager to test out the the timeline redesign allowing for the display of both future capable layers and subdaily imagery. In regard the the second feature, when implemented, it would be great if the animations would default to the selected subdaily time interval so that we would see all our PT6H data in the animation. This is especially desirable where chemical species have diurnal changes (due mostly to when humans are awake in that part of the world).
   As always, if there is anything that I can do you help test any/all upcoming features, please do not hesitate to let me know.

Thanks again for all your work on this!
Garth
https://worldview.acom.ucar.edu/

**Comment by rboller** [comment] 2019-01-30 17:19
Hi Garth, it's great to see your team's reuse of Worldview!  

We are indeed working on the timeline redesign which will include custom time intervals.  Check out #1496 for some of our current work.  Feel free to add comments there as you see fit.

Otherwise it doesn't show what the animation panel will look like yet, but I'll rename this ticket and keep it open to remind ourselves that it should behave as you suggest: to default to the currently selected interval.

Thanks for your suggestion!  We'll also try to keep you in the loop when we're ready to do some evaluation and testing.

**Comment by jasontk19** [comment] 2019-08-02 19:43
Looks like we addressed this as part of the timeline redesign work as intended.  Closing!

**Closed** 2019-08-02 19:43 UTC
