### ISSUE TITLE
Tooltip Above date input

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1659] opened 2019-03-08 00:07 UTC
**Describe the bug**
A Tooltip Above date input

**To Reproduce**
1. Click on day input

**Screenshots**
<img width="153" alt="screen shot 2019-03-07 at 7 01 04 pm" src="https://user-images.githubusercontent.com/3605988/53997917-0fae3980-410c-11e9-97c6-e27b5e497a62.png">

**Desktop (please complete the following information):**
 - OSX
 - Chrome v72

**Additional context**
On Prod: Version 2.13.0

**Comment by ZachTRice** [comment] 2019-03-08 11:55
I saw this the other day (Windows 10) but am unable to reproduce it now. I am currently running Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by minniewong** [comment] 2019-08-02 20:02
Fixed in v3.0.0

**Closed by minniewong** 2019-08-02 20:02 UTC
