### ISSUE TITLE
When switching between projections, rotation display does not update [map.rotate.9]

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#675] opened 2018-01-12 20:22 UTC
When you switch between arctic and antarctic projections, while each projection independently retains it's rotation, the number on the map controls that indicates the degrees of rotation does not change until you rotate the selected projection more.

**Comment by localjo** [comment] 2018-01-15 18:42
Additionally, if you switch to geographic projection in between the polar projections, the value displayed on the rotation control will default to the value for the last polar projection selected instead of the one you select.

**Comment by ZachTRice** [comment] 2018-01-16 15:21
Duplicate of #532

**Closed** 2018-01-16 15:21 UTC
Labels: bug
