### ISSUE TITLE
Option to refresh layer after set time period

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2892] opened 2020-05-14 17:19 UTC
**Is your feature request related to a problem? Please describe.**
Option to refresh layer tiles after set time period

**Describe the solution you'd like**
Have a `refreshTime` or tileTimeOut` key in the layer config that rerequests the layer after the said timeout. 

Implementation... This `refresh` class would be be extended from the OL tileload function
Would probably need to account for if a user leaves there window open...

**Describe alternatives you've considered**
N/A
**Additional context**
This may help: https://gis.stackexchange.com/a/256384

**Comment by minniewong** [comment] 2021-07-20 16:03
Duplicate of #389

**Closed by minniewong** 2021-07-20 16:03 UTC
Labels: new feature
