### ISSUE TITLE
Legend needs to accommodate at least 18 categories

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#663] opened 2018-01-10 18:02 UTC
A new land cover layer, which should be ready by March, will have 18 categories. Need to come up with a better solution for handling that many category color boxes. 
Fixing this should also close #523

**Comment by ZachTRice** [comment] 2018-01-10 18:04
Adding the following to the CSS will help the layout of the boxes.
```
.bank div.wv-palettes-legend { overflow: hidden }
.wv-palettes-class {
    float: left;
    margin-bottom: 8px;
}
```
The actual tooltip label is controlled by javascript and will need to be tweaked.

It might make sense to restructure the html a bit to accommodate this. There are better ways to structure this area.

**Comment by Benjaki2** [comment] 2018-01-10 18:09
duplicate of #626

**Comment by ZachTRice** [comment] 2018-01-10 18:11
Moved these comments to #626 and closing this issue.

**Closed by ZachTRice** 2018-01-10 18:11 UTC
